version: '3.1'

services:

        wordpress:
                image: wordpress:latest
                ports:
                        - 8080:80
                environment:
                        WORDPRESS_DB_PASSWORD: password
                volumes:
                # map any files and directories to the containers file system. Here, I am mapping a plugin
                # i am developing called bacol-utils-for-wp to the container. This allows me to edit the
                # plugin files on my local machine while viewig the results on the container.
                - ../bacol-utils-for-wp:/var/www/html/wp-content/plugins/bacol-utils-for-wp
                - ../literature-city:/var/www/html/wp-content/themes/literature-city
                  # - ./wp-config.php:/var/www/html/wp-config.php
        db:
                # grab the latest version of the mysql container
                image: mysql:latest
                environment:
                        MYSQL_ROOT_PASSWORD: password #must map to WORDPRESS_DB_PASSWORD
        phpmyadmin:
                image: phpmyadmin/phpmyadmin:latest
                ports:
                        - 9090:80
                links:
                        - db:mysql
                environment:
                        MYSQL_USERNAME: root
                        MYSQL_ROOT_PASSWORD: password #must map to mysql password
