version: '3.1'

services: 
    wordpress: 
        image: wordpress:latest
        ports:
            - 8080:80
        environment:
            WORDPRESS_DB_PASSWORD: password
        volumes:
            - ../bacol-utils-for-wp:/var/www/html/wp-content/plugins/bacol-wp
    mysql:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
